version: "3"
services:
  postgres:
    image: "postgres:13.2"
    restart: always
    environment:
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d/
    ports:
     - "5432:5432"
    networks:
      default:
  fhir:
    build: .
    restart: always
    ports:
      - "5005:5005"
    networks:
      default:
  keycloak:
    image: "quay.io/keycloak/keycloak:13.0.0"
    restart: always
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: keycloak
#      KEYCLOAK_USER: admin
#      KEYCLOAK_PASSWORD: admin
      PROXY_ADDRESS_FORWARDING: "true" #important for reverse proxy
    networks:
      default:
  nginx:
    image: "nginx:1.22@sha256:8c5a18dc716f05339547266429681d3797aaeb330837ecb8a418cded3f801876"
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx:/usr/share/nginx/html:ro
    ports: 
      - "80:80"
    networks:
      default:
        aliases:
          - "fakepkb.local" 
networks:
  default: